services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: hotel-db-sql
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Senior@Dev#2026!

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: hotel-azure-emulator
    hostname: azurite
    # O comando abaixo IGNORA a verificação de versão da API
    command: azurite --skipApiVersionCheck --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
